name = "ordersapp-backend"
main = "src/index.ts"
compatibility_date = "2026-04-02"

[[d1_databases]]
binding = "DB"
database_name = "order-db"
database_id = "6dfdc7ae-8c7c-486d-8d57-e6643d0237e3"
migrations_dir = "drizzle"
